apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mvc
        # image: demoaks0acr.azurecr.io/web-app:1.3
        # image: houssemdocker/webapp:111
        image: hajaraburmeileh/web-app:37
        # image: __ACR_NAME__.azurecr.io/__DOCKER_IMAGE__:__TAG__
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: nginx